<?xml version="1.0" encoding="UTF-8"?>
<testng-results skipped="2" failed="0" total="3" passed="1">
  <reporter-output>
  </reporter-output>
  <suite name="Default suite" duration-ms="54714" started-at="2019-01-16T01:21:48Z" finished-at="2019-01-16T01:22:43Z">
    <groups>
    </groups>
    <test name="Default test" duration-ms="54714" started-at="2019-01-16T01:21:48Z" finished-at="2019-01-16T01:22:43Z">
      <class name="com.qa.meschino.testcases.verifyLogin">
        <test-method status="PASS" signature="startup()[pri:0, instance:com.qa.meschino.testcases.verifyLogin@36ebc363]" name="startup" is-config="true" duration-ms="10568" started-at="2019-01-15T20:21:48Z" finished-at="2019-01-15T20:21:58Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- startup -->
        <test-method status="SKIP" signature="LoginTest(java.util.Hashtable)[pri:0, instance:com.qa.meschino.testcases.verifyLogin@36ebc363]" name="LoginTest" duration-ms="16" started-at="2019-01-15T20:21:58Z" data-provider="getData" finished-at="2019-01-15T20:21:58Z">
          <params>
            <param index="0">
              <value>
                <![CDATA[{Password=Test@123, Runmode=N, Expected=Success, UserName=neil@peter.com, Description=Verify that, system allows to login with valid Credentials, Result=}]]>
              </value>
            </param>
          </params>
          <exception class="org.testng.SkipException">
            <message>
              <![CDATA[Skipping Test case  as runmode is No]]>
            </message>
            <full-stacktrace>
              <![CDATA[org.testng.SkipException: Skipping Test case  as runmode is No
	at com.qa.meschino.testcases.verifyLogin.LoginTest(verifyLogin.java:42)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:80)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:714)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:901)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1231)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:127)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:111)
	at org.testng.TestRunner.privateRun(TestRunner.java:767)
	at org.testng.TestRunner.run(TestRunner.java:617)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:334)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:329)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:291)
	at org.testng.SuiteRunner.run(SuiteRunner.java:240)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1198)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1123)
	at org.testng.TestNG.run(TestNG.java:1031)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:114)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- org.testng.SkipException -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- LoginTest -->
        <test-method status="PASS" signature="endTest()[pri:0, instance:com.qa.meschino.testcases.verifyLogin@36ebc363]" name="endTest" is-config="true" duration-ms="1438" started-at="2019-01-15T20:21:58Z" finished-at="2019-01-15T20:22:00Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- endTest -->
        <test-method status="PASS" signature="startup()[pri:0, instance:com.qa.meschino.testcases.verifyLogin@36ebc363]" name="startup" is-config="true" duration-ms="9150" started-at="2019-01-15T20:22:00Z" finished-at="2019-01-15T20:22:09Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- startup -->
        <test-method status="PASS" signature="LoginTest(java.util.Hashtable)[pri:0, instance:com.qa.meschino.testcases.verifyLogin@36ebc363]" name="LoginTest" duration-ms="22767" started-at="2019-01-15T20:22:09Z" data-provider="getData" finished-at="2019-01-15T20:22:32Z">
          <params>
            <param index="0">
              <value>
                <![CDATA[{Password=Test@123, Runmode=Y, Expected=Unsuccessfull, UserName=aneel@x.com, Description=Verify that, system does not allow to login with Invalid Credentials, Result=}]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- LoginTest -->
        <test-method status="PASS" signature="endTest()[pri:0, instance:com.qa.meschino.testcases.verifyLogin@36ebc363]" name="endTest" is-config="true" duration-ms="802" started-at="2019-01-15T20:22:32Z" finished-at="2019-01-15T20:22:33Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- endTest -->
        <test-method status="PASS" signature="startup()[pri:0, instance:com.qa.meschino.testcases.verifyLogin@36ebc363]" name="startup" is-config="true" duration-ms="9057" started-at="2019-01-15T20:22:33Z" finished-at="2019-01-15T20:22:42Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- startup -->
        <test-method status="SKIP" signature="LoginTest(java.util.Hashtable)[pri:0, instance:com.qa.meschino.testcases.verifyLogin@36ebc363]" name="LoginTest" duration-ms="2" started-at="2019-01-15T20:22:42Z" data-provider="getData" finished-at="2019-01-15T20:22:42Z">
          <params>
            <param index="0">
              <value>
                <![CDATA[{Password=Test@123, Runmode=N, Expected=Success, UserName=qa@x.com, Description=Verify that, system does not allow to login with Invalid Credentials, Result=}]]>
              </value>
            </param>
          </params>
          <exception class="org.testng.SkipException">
            <message>
              <![CDATA[Skipping Test case  as runmode is No]]>
            </message>
            <full-stacktrace>
              <![CDATA[org.testng.SkipException: Skipping Test case  as runmode is No
	at com.qa.meschino.testcases.verifyLogin.LoginTest(verifyLogin.java:42)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:80)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:714)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:901)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1231)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:127)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:111)
	at org.testng.TestRunner.privateRun(TestRunner.java:767)
	at org.testng.TestRunner.run(TestRunner.java:617)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:334)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:329)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:291)
	at org.testng.SuiteRunner.run(SuiteRunner.java:240)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1198)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1123)
	at org.testng.TestNG.run(TestNG.java:1031)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:114)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- org.testng.SkipException -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- LoginTest -->
        <test-method status="PASS" signature="endTest()[pri:0, instance:com.qa.meschino.testcases.verifyLogin@36ebc363]" name="endTest" is-config="true" duration-ms="831" started-at="2019-01-15T20:22:42Z" finished-at="2019-01-15T20:22:43Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- endTest -->
      </class> <!-- com.qa.meschino.testcases.verifyLogin -->
    </test> <!-- Default test -->
  </suite> <!-- Default suite -->
</testng-results>
